import json
import pandas as pd
import time
import torch
torch.set_default_device('cpu')

from transformers import AutoModelForCausalLM, AutoTokenizer
from utils.evaluate_results import NO_ANSWER_MARKER, evaluate_results
from utils.prompt_builder import PromptBuilder
from utils.answer_processor import AnswerProcessor
from utils.confidence_scorer import ConfidenceScorer
from utils.span_matcher import SpanMatcher
from utils.extraction_agent import ExtractionAgent
from utils.analysis_agent import AnalysisAgent


class ModelManager:
    """Responsible for loading the LLM and running inference (single + batch).

    Returns both raw text **and** per-token confidence scores so that
    downstream components can make reject/accept decisions.
    """

    def __init__(self, model_name='meta-llama/Llama-3.2-3B-Instruct'):
        self.tokenizer = AutoTokenizer.from_pretrained(model_name, token=True)
        self.model = AutoModelForCausalLM.from_pretrained(
            model_name, dtype=torch.float16, token=True
        )
        self.model.config.pad_token_id = self.tokenizer.eos_token_id
        self.tokenizer.pad_token_id = self.tokenizer.eos_token_id

    # ── single-item inference ───────────────────────────────────────
    def generate_single(self, messages):
        """Run inference on a single chat-message list.

        Returns:
            str: The raw text generated by the model (new tokens only).
        """
        prompt_text = self.tokenizer.apply_chat_template(
            messages, add_generation_prompt=True, tokenize=False
        )
        inputs = self.tokenizer(
            prompt_text, return_tensors="pt", padding=True, truncation=True
        )

        with torch.no_grad():
            outputs = self.model.generate(
                input_ids=inputs["input_ids"],
                attention_mask=inputs["attention_mask"],
                max_new_tokens=50,
                do_sample=False,
            )

        new_tokens = outputs[0][inputs["input_ids"].shape[-1]:]
        return self.tokenizer.decode(new_tokens, skip_special_tokens=True)

    # ── batched inference with confidence scores ────────────────────
    def generate_batch(self, messages_list):
        """Run batched inference and return texts + confidence scores.

        Tokenizes all prompts together with left-padding so that
        generation starts at the same position for every sequence.

        Returns:
            tuple[list[str], list[float]]:
                (raw_texts, confidences) — one entry per input.
        """
        prompt_texts = [
            self.tokenizer.apply_chat_template(
                msgs, add_generation_prompt=True, tokenize=False
            )
            for msgs in messages_list
        ]

        original_padding_side = self.tokenizer.padding_side
        self.tokenizer.padding_side = "left"
        inputs = self.tokenizer(
            prompt_texts, return_tensors="pt", padding=True, truncation=True
        )
        self.tokenizer.padding_side = original_padding_side

        with torch.no_grad():
            outputs = self.model.generate(
                input_ids=inputs["input_ids"],
                attention_mask=inputs["attention_mask"],
                max_new_tokens=50,
                do_sample=False,
                return_dict_in_generate=True,
                output_scores=True,
            )

        prompt_len = inputs["input_ids"].shape[1]

        # Decode texts
        texts = []
        for i in range(len(messages_list)):
            new_tokens = outputs.sequences[i][prompt_len:]
            texts.append(
                self.tokenizer.decode(new_tokens, skip_special_tokens=True)
            )

        # Compute confidence scores
        confidence_scorer = ConfidenceScorer()
        confidences = confidence_scorer.compute_batch_confidences(
            outputs.scores, outputs.sequences, prompt_len,
            self.tokenizer.eos_token_id,
        )

        return texts, confidences


class SquadQARunner:
    """Orchestrates the two-agent QA pipeline.

    For each question, runs the full pipeline sequentially:
        1. ExtractionAgent — runs the first LLM call, collects structured
           observations (raw answer, confidence, grounding, span match).
        2. AnalysisAgent — receives the context, question, and observations,
           makes a second LLM call to decide the final answer.

    Both agents share the same ModelManager (single model load).
    """

    def __init__(self, model_manager, extraction_agent, analysis_agent):
        self.model_manager = model_manager
        self.extraction_agent = extraction_agent
        self.analysis_agent = analysis_agent

    def answer_single(self, context, question):
        """Process one (context, question) pair through both agents."""
        observation = self.extraction_agent.extract_single(context, question)
        return self.analysis_agent.analyze_single(context, question, observation)

    def run(self, data_filename):
        """Solve an entire SQuAD 2.0 CSV file using the two-agent pipeline.

        Each question goes through the full pipeline (extract → analyze)
        before moving to the next.

        Returns:
            str: Path to the results CSV.
        """
        df = pd.read_csv(data_filename)
        total = len(df)
        final_answers = []

        for idx, row in df.iterrows():
            context = row["context"]
            question = row["question"]

            # 1. Extraction Agent: first LLM call + evidence gathering
            observation = self.extraction_agent.extract_single(context, question)

            # 2. Analysis Agent: second LLM call for final decision
            answer = self.analysis_agent.analyze_single(context, question, observation)

            final_answers.append(answer)
            print(f"  [{len(final_answers)}/{total}] {answer[:60]}")

        df["final answer"] = final_answers

        out_filename = data_filename.replace('.csv', '-results.csv')
        df.to_csv(out_filename, index=False)
        print(f'final answers recorded into {out_filename}')
        return out_filename


# ── Initialise components ────────────────────────────────────────────
model_manager = ModelManager()
prompt_builder = PromptBuilder()
answer_processor = AnswerProcessor()
confidence_scorer = ConfidenceScorer(no_answer_threshold=-1.0)
span_matcher = SpanMatcher(min_similarity=0.6)

extraction_agent = ExtractionAgent(
    model_manager, prompt_builder, answer_processor, span_matcher,
)
analysis_agent = AnalysisAgent(model_manager)

runner = SquadQARunner(model_manager, extraction_agent, analysis_agent)

# Keep legacy references so nothing else breaks
model_name = 'meta-llama/Llama-3.2-3B-Instruct'
tokenizer = model_manager.tokenizer
model = model_manager.model


def generate_answer(messages):
    return model_manager.generate_single(messages)


def answer_single_question(context, question):
    return runner.answer_single(context, question)


def squad_qa(data_filename):
    return runner.run(data_filename)


if __name__ == '__main__':
    start_time = time.time()

    with open('config.json', 'r') as json_file:
        config = json.load(json_file)

    data = pd.read_csv(config['data'])
    sample = data.sample(n=config['sample_for_solution'])  # for grading will be replaced with 'sample_for_grading'
    sample_filename = config['data'].replace('.csv', '-sample.csv')
    sample.to_csv(sample_filename, index=False)

    out_filename = squad_qa(sample_filename)  # todo: the function you implement

    eval_out = evaluate_results(out_filename, final_answer_column='final answer')
    eval_out_list = [str((k, round(v, 3))) for (k, v) in eval_out.items()]
    print('\n'.join(eval_out_list))

    elapsed_time = time.time() - start_time
    print(f"time: {elapsed_time: .2f} sec")
